server:
  port: 8888
  servlet:
    context-path: /

spring:    
  profiles:    active: dev  mvc:
    static-path-pattern: /**
    favicon:
      enabled: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static,classpath:/resources/,file:${web.resource-path}
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
  servlet: 
    multipart: 
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 10MB
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis: 
  configuration:    call-setters-on-nulls: true
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.itechyou.cms.entity  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper: 
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging: 
  config: classpath:log4j2.yml


